#!/bin/bash

if [ -z "$1" ]
then
  directory="."
else
  directory="$1"
fi

echo "Информация о каталоге $directory:"
echo "-----------------------------------"
echo "Файлы:"
for file in "$directory"/*
do
  if [ -f "$file" ]
  then
    echo "$file"
  fi
done

echo "Директории:"
for dir in "$directory"/*
do
  if [ -d "$dir" ]
  then
    echo "$dir"
  fi
done

echo "Права доступа:"
echo "--------------"
for file in "$directory"/*
do
  if [ -f "$file" ]
  then
    echo "$file $(stat -c '%A' "$file")"
  fi
done

for dir in "$directory"/*
do
  if [ -d "$dir" ]
  then
    echo "$dir $(stat -c '%A' "$dir")"
  fi
done

